ALTER TABLE `tb_bag_treasure` CHANGE COLUMN `item_num` `item_num` INT(10) UNSIGNED NULL DEFAULT 0  , CHANGE COLUMN `level` `level` SMALLINT(5) UNSIGNED NULL DEFAULT 0  , CHANGE COLUMN `exp` `exp` INT(10) UNSIGNED NULL DEFAULT 0  , CHANGE COLUMN `refine_level` `refine_level` SMALLINT(5) UNSIGNED NULL DEFAULT 0  ;



